/**
 * Language Data for Resume Website Template
 * This file generates language data from the config.js file
 * DO NOT EDIT THIS FILE - All customization should be done in config.js
 */

// Generate language data from config
function generateLanguageData() {
    const languageData = {
        en: {
            nav: {
                contact: "Contact Me",
                summary: "Summary",
                overview: "Overview",
                workHistory: "Work History",
                skills: "Skills",
                languages: "Languages",
                timeline: "Timeline"
            },
            header: {
                title: resumeConfig.personal.jobTitle.en,
                experience: `${resumeConfig.personal.yearsExperience} Years of Professional Experience`
            },
            sections: {
                summary: {
                    title: "Summary",
                    content: resumeConfig.personal.summary.en
                },
                overview: {
                    title: "Overview",
                    yearsExperience: "Years of professional experience"
                },
                workHistory: {
                    title: "Work History",
                    jobs: resumeConfig.workHistory.en
                },
                skills: {
                    title: "Skills",
                    skillsList: resumeConfig.skills.en
                },
                languages: {
                    title: "Languages",
                    languagesList: resumeConfig.languages.en
                },
                timeline: {
                    title: "Timeline",
                    timelineItems: resumeConfig.timeline.en
                }
            }
        },
        fr: {
            nav: {
                contact: "Me Contacter",
                summary: "Résumé",
                overview: "Aperçu",
                workHistory: "Expérience Professionnelle",
                skills: "Compétences",
                languages: "Langues",
                timeline: "Chronologie"
            },
            header: {
                title: resumeConfig.personal.jobTitle.fr,
                experience: `${resumeConfig.personal.yearsExperience} Années d'Expérience Professionnelle`
            },
            sections: {
                summary: {
                    title: "Résumé",
                    content: resumeConfig.personal.summary.fr
                },
                overview: {
                    title: "Aperçu",
                    yearsExperience: "Années d'expérience professionnelle"
                },
                workHistory: {
                    title: "Expérience Professionnelle",
                    jobs: resumeConfig.workHistory.fr
                },
                skills: {
                    title: "Compétences",
                    skillsList: resumeConfig.skills.fr
                },
                languages: {
                    title: "Langues",
                    languagesList: resumeConfig.languages.fr
                },
                timeline: {
                    title: "Chronologie",
                    timelineItems: resumeConfig.timeline.fr
                }
            }
        }
    };

    return languageData;
}

// Make languageData available globally
window.languageData = generateLanguageData();
